server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force-response: true
spring:
  config:
    import:
    - optional:classpath:/oauth.yml
    
mybatis:
  mapper-locations: 
    - classpath:/mybatis/**/*.xml

    
logging:
  level:
    org.mybatis.spring.SqlStatementInterceptor: TRACE

# yaml/yml 파일 - Thymeleaf 설정
thymeleaf:
  cache: false
  check-template-location: true
  prefix: classpath:/templates/
  suffix: .html
  enabled: true
